{
 "title": "plotly_data_analysis",
 "time": { "from": "2023-07-12T05:11:06.416Z", "to": "2023-08-05T16:14:02.311Z" },
 "panels": [
  {
   "title": "Deviation analysis pH 4.00",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", ph_high_res, name FROM probe_data WHERE  ph_high_res < 15.1 AND ph_high_res > 0 AND name = 'probe1' and ph_should_be = 4.00"
    },
    {
     "rawSql": "SELECT \"time\", ph_high_res, name FROM probe_data WHERE  ph_high_res < 15.1 AND ph_high_res > 0 AND name = 'probe2' and ph_should_be = 4.00"
    }
   ]
  },
  {
   "title": "Deviation analysis pH 7.01",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", ph_high_res, name FROM probe_data WHERE  ph_high_res < 15.1 AND ph_high_res > 0 AND name = 'probe1' and ph_should_be = 7.01"
    },
    {
     "rawSql": "SELECT \"time\", ph_high_res, name FROM probe_data WHERE  ph_high_res < 15.1 AND ph_high_res > 0 AND name = 'probe2' and ph_should_be = 7.01"
    }
   ]
  },
  {
   "title": "Deviation analysis pH 9.93",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", ph_high_res, name FROM probe_data WHERE  ph_high_res < 15.1 AND ph_high_res > 0 AND name = 'probe1' and ph_should_be = 9.93"
    },
    {
     "rawSql": "SELECT \"time\", ph_high_res, name FROM probe_data WHERE  ph_high_res < 15.1 AND ph_high_res > 0 AND name = 'probe2' and ph_should_be = 9.93"
    }
   ]
  },
  {
   "title": "Deviation analysis pH 3.98",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", ph_high_res, name FROM probe_data WHERE  ph_high_res < 15.1 AND ph_high_res > 0 AND name = 'probe1' and ph_should_be = 3.98"
    },
    {
     "rawSql": "SELECT \"time\", ph_high_res, name FROM probe_data WHERE  ph_high_res < 15.1 AND ph_high_res > 0 AND name = 'probe2' and ph_should_be = 3.98"
    }
   ]
  },
  {
   "title": "Deviation analysis pH 5.70",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", ph_high_res, name FROM probe_data WHERE  ph_high_res < 15.1 AND ph_high_res > 2 AND name = 'probe1' and ph_should_be = 5.70"
    },
    {
     "rawSql": "SELECT \"time\", ph_high_res, name FROM probe_data WHERE  ph_high_res < 15.1 AND ph_high_res > 2 AND name = 'probe2' and ph_should_be = 5.70"
    }
   ]
  }
 ]
}